# Generated by Django 2.2 on 2020-02-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='update_type',
            field=models.CharField(choices=[('daily', 'Daily, Every day at 5PM'), ('weekly', 'Weekly, Every Monday'), ('monthly', 'Monthly, First day of Month')], default='daily', max_length=32),
        ),
    ]
